### ISSUE TITLE
Mobile Menu Refactoring

### ISSUE THREAD

**Issue by TheMightyPenguin** [hashlabs/hashlabs.github.io#17]
# Context

The Mobile Menu, was implemented whitout a design reference, just to have a working one while the design was made. Once this design is finished, the menu should be implemented again.

Design here:
![menu mobile](https://cloud.githubusercontent.com/assets/11748696/23800265/068d6c94-0582-11e7-8e50-d67ee5e70557.png)

## Acceptance Criteria

* Refactor mobile menu once the design is ready.
* Menu should be implemented under design guidelines.

**Comment by duranmla** [comment]
This has been closed with #24
