### ISSUE TITLE
Make lead video do a natural loop

### ISSUE THREAD

**Issue by TheMightyPenguin** [hashlabs/hashlabs.github.io#22]
# Context

The video on the lead section, should have a perfect loop after playing for a certain time. Currently, the video that is available doesn't have the proper structure to loop it, so I already let our designer know about this and she is working on the new video. As soon as it's done this should be implemented.

## Acceptance Criteria

* Video loop should look natural.

**Comment by orlando** [comment]
@duranmla is this done?. If not work with @Marilia  on getting this ready

**Comment by duranmla** [comment]
@orlando @Marilia is already working on it

**Comment by orlando** [comment]
@duranmla can we update the project please?, this ticket is On Deck at the moment

**Comment by Marilia** [comment]
Ya @TheMightyPenguin tiene el video, estoy esperando que me confirme que todo ok con el espacio para el loop porque en el ultimo frame se veia brusco el cambio cuando comenzaba de nuevo el loop, ya lo corregi espero q me avise

**Comment by duranmla** [comment]
@TheMightyPenguin why we haven't close this one?

**Comment by TheMightyPenguin** [comment]
Closed by #37
