### ISSUE TITLE
Refactor variables

### ISSUE THREAD

**Issue by TheMightyPenguin** [hashlabs/hashlabs.github.io#25]
# Context

Refactor some SASS variables, to use bootstrap configurable settings, as this is a better practice.

## Acceptance Criteria

* Code should use more defaults from bootstrap.
* Bootstrap settings file should have more variables defined.

**Comment by duranmla** [comment]
Besides, I saw some colors naming like `$organge-accent` we use http://sipapp.io/ to handle color variable names, please try to find something web o for linux that give you better names, if you do not find anything please DM me in slack with the colors and I will give you the names while we figure it out something better

**Comment by duranmla** [comment]
@TheMightyPenguin While you do this please also remove all the stuff we are not using, code, assets, etc...

**Comment by duranmla** [comment]
I will delete this ticket as it is not longer valid
