### ISSUE TITLE
Link is overflowing image

### ISSUE THREAD

**Issue by orlando** [hashlabs/hashlabs.github.io#28]
# Context

![image](https://cloud.githubusercontent.com/assets/849872/23882282/35b6155c-0825-11e7-9284-0f2717a5b295.png)

## Acceptance Criteria

* Links should be the same size as the images

**Comment by duranmla** [comment]
Just to be more clear, we should avoid that clicking within the margins open the link @TheMightyPenguin so for this case make sure the image occupied the same space as the anchor tag

**Comment by TheMightyPenguin** [comment]
This issue has been closed with #34
