### ISSUE TITLE
Add missing videos

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#36]
# Context

Add videos to satisfy the services page. following the below format:

```
ruby: ruby, rails, bootstrap (mismo video que rails)
golang: golang, aws, rabbitmq
javascript: javascript react, redux
rails: rails, ruby, bootstrap (mismo video que ruby)
node: node, javascript, react
react: react, redux, javascript
react_native: react_native, swift, javascript
bootstrap: bootstrap, javascript, scss
sass: sass, bootstrap, node
devops: docker, terraform, aws
```

## Acceptance Criteria

* Videos need to be webm and mp4

**Comment by Marilia** [comment]
Ya @TheMightyPenguin tiene los videos de

* Ruby/Rails
* Golang
* Javascript
* Node
* React
* React Native
* Sass
* Devops

estoy terminando el de bootstrap que fue el q me falto xq no estaba segura que era Scss

**Comment by Marilia** [comment]
estos issues se cerraron luego del #38
