### ISSUE TITLE
Design for 404

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#40]
# Context

![banners_and_alerts_and_slack_-_hash_labs](https://cloud.githubusercontent.com/assets/1425162/24016353/28927570-0a62-11e7-81ac-3251cb64becb.jpg)

We need a better 404 page

## Acceptance Criteria

* 404 page should be elaborated

**Comment by Marilia** [comment]
zpl://screen?pid=5888b73ba8de3a354ef67567&sid=5978f1646f22e00c49cf9ed9
