### ISSUE TITLE
Images needed for lead section on phones and tablet

### ISSUE THREAD

**Issue by TheMightyPenguin** [hashlabs/hashlabs.github.io#53]
# Context

As the HTML5 video player is not consistent enough yet across all mobile devices, we need images to replace it on these devices (tablets, phones, etc...). We basically need one image per video, on the point where the confused workers are talking to hash labs workers

## Acceptance Criteria

* Each video should have a corresponding image to be used as fallback

**Comment by duranmla** [comment]
We are not doing this anymore
