### ISSUE TITLE
As a User I want to see a Services Page so that I can know Hash Labs' Services

### ISSUE THREAD

**Issue by orlando** [hashlabs/hashlabs.github.io#64]
# Context

We want to implement a services page that groups everything we do. The services we offer are development services in the following languages/frameworks

* Ruby/Rails
* Go
* React/React Native

We will have a page that has the same goal as https://thoughtbot.com/services

## Acceptance Criteria

* Design for this page
* Implementation for this page

**Comment by Marilia** [comment]
https://zpl.io/ZalxXp
