### ISSUE TITLE
As a User I want to see a specific page for each Service Hash Labs provide so that I have more information related to this Service

### ISSUE THREAD

**Issue by orlando** [hashlabs/hashlabs.github.io#67]
# Context

We want to create Service specific pages like thoughtbot does (ex. https://thoughtbot.com/services/react-native). These pages should be well presented and with some animations to catch the eye of the visitors. The goal of these pages is to show to users:

* Why we work with a certain technology
* Why we prefer a certain technology and when
* How we use this technology

The services we provide at the moment are

* [x] Ruby/Rails development
* [x] React/React Native development
* [x] Go development

## Acceptance Criteria

* Design a service page for each service we provide
* Implement each service page

**Comment by Marilia** [comment]
Ruby services page  https://zpl.io/ZiPxkR
React services page   https://zpl.io/1Ii0Kk

**Comment by Marilia** [comment]
Go services page https://zpl.io/Z1FrKWl
Rect native services page https://zpl.io/2jawDs

**Comment by Marilia** [comment]
Rails zpl://screen?pid=5888b73ba8de3a354ef67567&sid=595150dd48074bdc3ce6b13a
React zpl://screen?pid=5888b73ba8de3a354ef67567&sid=5951c7159cc69f3564b13feb
Go zpl://screen?pid=5888b73ba8de3a354ef67567&sid=595422ebb8636253cb5f58f8
React Native zpl://screen?pid=5888b73ba8de3a354ef67567&sid=595423778c48353c1e60bdaf
