### ISSUE TITLE
As a User I should be able to see a 'Our Process' page, that explains how our development works

### ISSUE THREAD

**Issue by orlando** [hashlabs/hashlabs.github.io#68]
# Context

Our development process is comprised of the following steps

1. Initial planning
  * Scope definition
  * Initial Roadmap
  * Initial mockups
  * Initial staging/development environments
2. Iterative development
  * Weekly sprints
  * Continuous delivery
3. Initial release
  * Production environments
  * Application Monitoring
  * Application Metrics
4. Monitoring and Data gathering
  * Dashboards for App Metrics
  * Dashboards for App Analytics

The idea is to create a vertical scrolling site that has animations related to each step, as you scroll, objects will be moving (something like a 'parallax scroll' (you can search for this in google for examples))

**Comment by Marilia** [comment]
avances 
https://zpl.io/Z2qUSBi

**Comment by Marilia** [comment]
https://zpl.io/Z1ft6I1
