### ISSUE TITLE
Implement new desktop home page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#70]
# Context

We need to refactor the home page to looks like design: 

zpl://screen?pid=5888b73ba8de3a354ef67567&sid=5947b9836b0dde9419b090ee
https://zpl.io/1qUBdV

_See blue notes for further details about implementation_

## Acceptance Criteria

* Implement new desktop home

**Comment by orlando** [comment]
@duranmla we are not going to use the video, I removed that from the Acceptance Criteria
