### ISSUE TITLE
Create new services page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#72]
# Context

Add the new page as the design suggests:

https://zpl.io/ZalxXp

_See blue notes for further details about implementation_

## Acceptance Criteria

* Implement new services page that meet all responsive guidelines

**Comment by duranmla** [comment]
@Marilia I was about to make a PR for services page but I couldn't make cause I feel there may be some pending changes, below I will list you the current state of the service page (almost done). I feel that we may want to update the SCG icons to have more contrast cause they are barely visible for mobile devices and tablets. besides, the tablet design hasn't been updated so I am not sure if you are ok on how is looking now. Please need your feedback ASAP in order to do not delay the project and be able to deliver on time. Thanks!

## Media

**Mobile**

![hash_labs___hassle_free_software_engineering](https://user-images.githubusercontent.com/1425162/28755364-5a4e447e-7527-11e7-8585-d4227bae96ad.jpg)

**Tablet**
![hash_labs___hassle_free_software_engineering](https://user-images.githubusercontent.com/1425162/28755370-749fb5ec-7527-11e7-85b1-1654509095ca.jpg)

**Desktop**
![hash_labs___hassle_free_software_engineering](https://user-images.githubusercontent.com/1425162/28755374-8928a2e4-7527-11e7-836f-764aa5d03ccb.jpg)

**Desktop 4K**
![hash_labs___hassle_free_software_engineering](https://user-images.githubusercontent.com/1425162/28755379-ae209bf6-7527-11e7-8fe1-4d8ebab82b39.jpg)

**Comment by carlows** [comment]
I've already updated the footer to look like the tablet design (2 columns) in my branch for the home page.

Besides, what did you add to the code of title with icon to look like that in mobile?

![image](https://user-images.githubusercontent.com/4183514/28755588-303be8bc-752c-11e7-90ca-2589a424f94a.png)

Icon is on top. I used your snippet but icon was in the same line on mobile res.

**Comment by duranmla** [comment]
@Carlows yes I have updated the code so in mobile it will look as expected, the update of the footer is merged? Cause I didn't receive any changes.

**Comment by duranmla** [comment]
@Carlows besides you can check out the code at https://github.com/hashlabs/hashlabs.github.io/blob/ad/services/_sass/_objects--type.scss#L40
