### ISSUE TITLE
Refactor hire us page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#74]
# Context

Add the new page as the design suggests:

https://zpl.io/ZQgF4v

Also screen design showing form validations https://zpl.io/1X9G5Y

_See blue notes for further details about implementation_

## Acceptance Criteria

* Implement new "hire us" page that meets all responsive guidelines
* Form should validate and show feedback
* When form succesfully submits, it should take the user to a "thanks" page

**Comment by TheMightyPenguin** [comment]
Already implemented this page including form validations and errors feedback, but waiting for @Marilia to upload "thanks" page design, gonna start working on #75 meanwhile

**Comment by duranmla** [comment]
@Marilia please clarify this ASAP

**Comment by TheMightyPenguin** [comment]
@Marilia just uploaded the design here zpl://screen?pid=5888b73ba8de3a354ef67567&sid=597b932fa04889ea6509637c :+1:, however gonna keep working on #75 to prevent blocking any issues (as #74 doesn't block any, but #75 might)
