### ISSUE TITLE
Create layout for service specific page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#75]
# Context

We need to create a basic customizable layout to be able to create easily pages like the ones below:

https://zpl.io/ZiPxkR
https://zpl.io/1Ii0Kk
https://zpl.io/Z1FrKWl
https://zpl.io/2jawDs

_See blue notes for further details about implementation_

## Acceptance Criteria

* Add layout to create service specific page
* Add a single service page for each of the design above (no animation required)

**Comment by TheMightyPenguin** [comment]
@Marilia when you can please upload or pass me these images (the bullets for each service page list). Also if they could be on svg format that would be great!

![screen shot 2017-07-28 at 8 55 14 pm](https://user-images.githubusercontent.com/11748696/28740771-2b6a822c-73d7-11e7-8481-27653f814c46.png)
![screen shot 2017-07-28 at 8 55 24 pm](https://user-images.githubusercontent.com/11748696/28740772-2b7280b2-73d7-11e7-833e-0a4f351f8cc7.png)
![screen shot 2017-07-28 at 8 55 31 pm](https://user-images.githubusercontent.com/11748696/28740773-2b76c41a-73d7-11e7-953b-3f30acdfaeef.png)
