### ISSUE TITLE
Add animation for rails service specific page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#76]
# Context

Service specific pages have animations in this case we need to implement the one for the rails page see the blue note for details about animation

https://zpl.io/ZiPxkR

## Acceptance Criteria

* Meet design guidelines within zeplin design to create animation

**Comment by TheMightyPenguin** [comment]
Assuming the ruby image is an svg, animation could be done through keyframes (to change red tones sequentially), or using a library like animejs or greensocks to handle a more complex animation (random color perhaps).

Also the little stars (or glow thingies) can be animated through css aswell, or using any of the 2 mentioned libraries.

I don't think this animation will require a canvas
