### ISSUE TITLE
Add animation for react specific page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#77]
# Context

Service specific pages have animations, in this case, we need to implement the one for the react page see the blue note for details about animation

https://zpl.io/1Ii0Kk

## Acceptance Criteria

* Meet design guidelines within zeplin design to create animation

**Comment by TheMightyPenguin** [comment]
This animation could be done simply using a css keyframe, or using a library like animejs or greensocks.

A canvas could be used tho, to animate the little dots as if they were something like falling snow or just moving randomly
