### ISSUE TITLE
Add animation for go specific page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#78]
# Context

Service specific pages have animations, in this case, we need to implement the one for the go page see the blue note for details about animation

https://zpl.io/Z1FrKWl

## Acceptance Criteria

* Meet design guidelines within zeplin design to create animation

**Comment by TheMightyPenguin** [comment]
Depending on how complex this animation is decided to be, a library like greensocks could perhaps be used to make gopher eyes follow the mouse.
