### ISSUE TITLE
Add animation for react native specific page

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#79]
# Context

Service specific pages have animations, in this case, we need to implement the one for the react native page see the blue note for details about animation

https://zpl.io/2jawDs

## Acceptance Criteria

* Meet design guidelines within zeplin design to create animation

**Comment by TheMightyPenguin** [comment]
A canvas is needed here to make the particles on the background move, also the glow effect can be achieved trough css using something like [this](https://codepen.io/TheMightyPenguin/pen/NvxKLz?editors=0100), also the react native logo could rotate using a css keyframe to animate it.

**Comment by TheMightyPenguin** [comment]
As the design suggests that particles are on 2 separate groups, the algorithm to generate those particle systems and animate them could be something like:

1. Generate N clusters of particles on bounding dimensions (bound width and height)
2. Connect each particle to the closest 5 (having a max distance to establish a connection perhaps)
3. On each cluster update each particle position (move randomly smoothly inside cluster bound area)
4. Draw and go to Step 3

Step 3 and 4 are our update loop

**Comment by duranmla** [comment]
The link posted doesn't show me anything @TheMightyPenguin besides, make sure to satisfy the minimum requirement before making something more complex. On top of that, make sure to keep constant sync with the whole team so we will ensure we invest time in an approach that worth
