### ISSUE TITLE
Add navbar component to the site

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#8]
![desktop_home_v2_-_hash_labs_v5_-_zeplin](https://cloud.githubusercontent.com/assets/1425162/23520292/b12f3d36-ff50-11e6-95cd-fc61d2331975.jpg)

_checkout designs to see mobile layout_

**Comment by TheMightyPenguin** [comment]
Done with PR #16

**Comment by TheMightyPenguin** [comment]
Done with PR #16
