### ISSUE TITLE
Add footer of the site

### ISSUE THREAD

**Issue by duranmla** [hashlabs/hashlabs.github.io#9]
Make sure our footer is stick to the bottom, so regardless the content it will be displayed at the bottom of the screen.

![desktop_home_v2_-_hash_labs_v5_-_zeplin](https://cloud.githubusercontent.com/assets/1425162/23520340/eb60eb8a-ff50-11e6-88e4-e00f95818c2b.jpg)

_check design at zeplin to look for mobile layout_

**Comment by TheMightyPenguin** [comment]
Done with PR #19
