### ISSUE TITLE
Add SEO meta tags from v6 site

### ISSUE THREAD

**Issue by TheMightyPenguin** [hashlabs/hashlabs.github.io#90]
# Context

Add meta tags similar to those on the simian-ci site, they can be seen here https://github.com/simian-ci/simian-ci.github.io/blob/master/_includes/head.html and here https://github.com/simian-ci/simian-ci.github.io/blob/master/_includes/social-tags.html

## Acceptance Criteria

* Head of the rendered site should have these meta tags

**Comment by duranmla** [comment]
We need to clarify how to add descriptions for specific pages, will do that but in meanwhile I won't close this yet
